#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d    󰊢 󰃇

bspc config border_width        1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set the default layout to grid
bspc config automatic_scheme spiral
bspc config initial_polarity second_child
bspc config borderless_monocle true
bspc config gapless_monocle true

#Autostart Apllication
sxhkd &
picom --config /home/dhruv/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a brave desktop='^3'
